name: CI
on:
  - push
  - pull_request
jobs:
  stylua:
    name: StyLua
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4

      - name: Format with stylua
        uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: false

      - run: |
          stylua lua --config-path=.stylua.toml
  luacheck:
    name: Luacheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4

      - name: Prepare
        run: |
          sudo apt-get update
          sudo apt-get install luarocks -y
          sudo luarocks install luacheck

      - name: Run Luacheck
        run: luacheck lua/ --globals vim
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3

      - name: Install Neovim
        uses: folke/github/neovim@main

      - name: Run Tests
        run: |
          nvim -l scripts/minitest.lua
